export interface LogisticsFallbackSeed {
  name: string;
  occurrences: number;
}

export const FALLBACK_CLIENT_SEEDS: LogisticsFallbackSeed[] = [
  { name: "DELTA BLAU", occurrences: 835 },
  { name: "HARRIE GOESTEN", occurrences: 263 },
  { name: "KOLLAGMBH", occurrences: 225 },
  { name: "PRIM", occurrences: 134 },
  { name: "SRPM NEGOCE", occurrences: 130 },
  { name: "LEGUERINAIS", occurrences: 114 },
  { name: "MORA FRERES", occurrences: 93 },
  { name: "BOULET", occurrences: 86 },
  { name: "DIEGO MARTINEZ", occurrences: 86 },
  { name: "PIEDOR", occurrences: 86 },
  { name: "ESPALMEX", occurrences: 83 },
  { name: "COFRULY", occurrences: 79 },
  { name: "FRUTASA", occurrences: 73 },
  { name: "KOLLA GMBH", occurrences: 67 },
  { name: "FRULEXXO", occurrences: 54 },
  { name: "COBANA", occurrences: 48 },
  { name: "VAN OOIJEN", occurrences: 47 },
  { name: "LACOUR", occurrences: 46 },
  { name: "URIA", occurrences: 30 },
  { name: "PICOLITO", occurrences: 26 },
  { name: "GEMPERLE", occurrences: 24 },
  { name: "RAFAEL LOPEZ", occurrences: 19 },
  { name: "KOLLA AG", occurrences: 16 },
  { name: "ALMONTE", occurrences: 11 },
  { name: "SURFRUIT", occurrences: 10 },
  { name: "KOLLA VALENCIA", occurrences: 9 },
  { name: "BELCAIRE", occurrences: 8 },
  { name: "PRIM SELECT", occurrences: 5 },
  { name: "BERKANE", occurrences: 4 },
  { name: "FRUTAS ANTONIO", occurrences: 3 },
  { name: "GUFRESCO", occurrences: 3 },
  { name: "HM DISTRIBUTION", occurrences: 3 },
  { name: "INDIGO FOOD", occurrences: 3 },
  { name: "UNIVERSAL", occurrences: 3 },
  { name: "ALYCA", occurrences: 2 },
  { name: "ARESCA", occurrences: 2 },
  { name: "AU PETIT", occurrences: 2 },
  { name: "ELADIO MALAGA", occurrences: 2 },
  { name: "FRUTAS DIEGO MARTINEZ", occurrences: 2 },
  { name: "MASTERFRUIT", occurrences: 2 },
  { name: "MASTERFRUITS", occurrences: 2 },
  { name: "MUÑOZ GUILLEN", occurrences: 2 },
  { name: "PREALPINA", occurrences: 2 },
  { name: "AYUSO Y MURILLO", occurrences: 1 },
  { name: "CARRION", occurrences: 1 },
  { name: "CITRAN", occurrences: 1 },
  { name: "CITRUS NOSTRUM", occurrences: 1 },
  { name: "CORDEIRO FILHOS", occurrences: 1 },
  { name: "CORDERO SIERRA", occurrences: 1 },
  { name: "CUELLO", occurrences: 1 },
  { name: "EDEKA", occurrences: 1 },
  { name: "FRUIT TEAM", occurrences: 1 },
  { name: "FRUMAR CÍTRICA", occurrences: 1 },
  { name: "GEFRUITS ERIKTRANS", occurrences: 1 },
  { name: "GUADEX", occurrences: 1 },
  { name: "HORTICOLAS EL VIEJO", occurrences: 1 },
  { name: "MERCADONA ANTEQUERA ACOTRAL", occurrences: 1 },
  { name: "MERCADONA HUEVAR", occurrences: 1 },
  { name: "MONLOUP", occurrences: 1 },
  { name: "ONLY YOU", occurrences: 1 },
  { name: "QUALITOR", occurrences: 1 },
  { name: "SODIPRAL SOCAFNA", occurrences: 1 },
  { name: "VAN OOIJEN CITRUS BV", occurrences: 1 },
];

export const FALLBACK_CARRIER_SEEDS: LogisticsFallbackSeed[] = [
  { name: "PRIMEVER", occurrences: 361 },
  { name: "SOCAFNA", occurrences: 203 },
  { name: "MESGUEN", occurrences: 185 },
  { name: "ROCA", occurrences: 177 },
  { name: "MERISOL 2", occurrences: 140 },
  { name: "EL MOSCA", occurrences: 109 },
  { name: "JANVAL", occurrences: 109 },
  { name: "CARRION", occurrences: 98 },
  { name: "GUERY", occurrences: 78 },
  { name: "RUNGIS - PACO CANO", occurrences: 65 },
  { name: "PROLOGISTIC", occurrences: 56 },
  { name: "CANYAES", occurrences: 50 },
  { name: "PACO CANO", occurrences: 47 },
  { name: "PASCAL LOGISTIC", occurrences: 43 },
  { name: "HANOS - EL MOSCA", occurrences: 38 },
  { name: "RUNGIS - ANTONIO CANO", occurrences: 38 },
  { name: "BLANCHER", occurrences: 33 },
  { name: "LYON - PACO CANO", occurrences: 30 },
  { name: "SERRE PILAIRE", occurrences: 29 },
  { name: "PUJOL", occurrences: 28 },
  { name: "ANTONIO CANO", occurrences: 26 },
  { name: "LILLE - CANO", occurrences: 26 },
  { name: "HOEKSTRA", occurrences: 21 },
  { name: "ESPALMEX", occurrences: 17 },
  { name: "BERTHAUD", occurrences: 16 },
  { name: "LILLE - PACO CANO", occurrences: 15 },
  { name: "PORTUGAL - DEFRANCIS", occurrences: 15 },
  { name: "LILLE - ANTONIO CANO", occurrences: 14 },
  { name: "EUROLOMA", occurrences: 13 },
  { name: "KOORNSTRA - SAGATRANS", occurrences: 10 },
  { name: "MONTIEL", occurrences: 10 },
  { name: "TOLOUSE - CANO", occurrences: 10 },
  { name: "VALIENTE", occurrences: 10 },
  { name: "ANDRETTA - ALCONCHEL", occurrences: 9 },
  { name: "RIEL - NAVARRO VEGA", occurrences: 9 },
  { name: "EL MOSCA - ANBERAN", occurrences: 7 },
  { name: "GETRU", occurrences: 7 },
  { name: "LYON - ANTONIO CANO", occurrences: 7 },
  { name: "GENARO", occurrences: 6 },
  { name: "LONDRES - MIRPA - CARRION", occurrences: 6 },
  { name: "LYON - PACO CANO - TRANSAYSA", occurrences: 6 },
  { name: "RIEL - NAVARRO", occurrences: 6 },
  { name: "EL MOSCA - ABERAN", occurrences: 5 },
  { name: "KINI", occurrences: 5 },
  { name: "RIEL - TIRCARHE", occurrences: 5 },
  { name: "SERVICOM", occurrences: 5 },
  { name: "CANYAES - ALCONCHEL", occurrences: 4 },
  { name: "FRUCTSERVICE - SAGATRANS", occurrences: 4 },
  { name: "LOGISMERCAN", occurrences: 4 },
  { name: "PORTUGAL - TRILLO", occurrences: 4 },
  { name: "RLC", occurrences: 4 },
  { name: "TRANSAYSA", occurrences: 4 },
  { name: "BLAZQUEZ", occurrences: 3 },
  { name: "KOORNSTRA", occurrences: 3 },
  { name: "MAPAPADRAO", occurrences: 3 },
  { name: "TRILLO", occurrences: 3 },
  { name: "ANECOOP", occurrences: 2 },
  { name: "DEFRANCIS", occurrences: 2 },
  { name: "ISABEL ALONSO", occurrences: 2 },
  { name: "PARRILLA", occurrences: 2 },
  { name: "RIEL", occurrences: 2 },
  { name: "SUMMUM", occurrences: 2 },
  { name: "TRANSPORT LAUZIER", occurrences: 2 },
];
